MODEL:
  PIXEL_STD: [57.375, 57.120, 58.395]
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  ANCHOR_GENERATOR:
    SIZES: [[32], [64], [128], [256], [512]]
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]
  RPN:
    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
    PRE_NMS_TOPK_TRAIN: 2000
    PRE_NMS_TOPK_TEST: 1000
    POST_NMS_TOPK_TRAIN: 1500
    POST_NMS_TOPK_TEST: 1000
  KEYPOINT_ON: True
  ROI_HEADS:
    NAME: "StandardROIHeads"
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    NUM_CLASSES: 2
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
    SMOOTH_L1_BETA: 0.5
  ROI_KEYPOINT_HEAD:
    NUM_KEYPOINTS: 1
DATASETS:
  TRAIN: ("hh_train",)
  TEST: ("hh_test",)
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.00025
  MAX_ITER: 20000
TEST:
  EVAL_PERIOD: 2500
  KEYPOINT_OKS_SIGMAS: [0.025]
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
VERSION: 2
